- name: configure backend server
  hosts: backend.guru97s.cloud
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enabling nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.dnf: # only works for redhat enterprise
        name: nodejs
        state: installed
    
    - name: creating expense user
      ansible.builtin.user:
        name: expense

    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory  # if mention directory, directory will be created on path /app and if you mention absent in state, then directory will be deleted

    - name: downloading backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    
    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip # by default checks in ansible server
        dest: /app
        remote_src: yes # by declaring remote_src: yes , it will checks in remote server and unarchive it on remote server